import { Company, SubscriptionPlan, Job, Worker, InventoryItem, Invoice, ChatMessage, Notification, Document, ServiceAgreement, EmailTemplate, User, Customer, Estimate, Communication } from './types';

export const users: User[] = [
  { id: 'sa1', name: 'Marcus Chen', email: 'marcus@fieldpro.io', role: 'super_admin', phone: '(555) 100-0001' },
  { id: 'a1', name: 'Sarah Mitchell', email: 'sarah@mitchell-plumbing.com', role: 'admin', companyId: 'c1', phone: '(555) 200-0001' },
  { id: 'a2', name: 'David Rodriguez', email: 'david@sparkvolt.com', role: 'admin', companyId: 'c2', phone: '(555) 200-0002' },
  { id: 'a3', name: 'Emma Thompson', email: 'emma@coolbreeze.com', role: 'admin', companyId: 'c3', phone: '(555) 200-0003' },
  { id: 'w1', name: 'Jake Morrison', email: 'jake@mitchell-plumbing.com', role: 'field_worker', companyId: 'c1', phone: '(555) 300-0001' },
  { id: 'w2', name: 'Carlos Rivera', email: 'carlos@mitchell-plumbing.com', role: 'field_worker', companyId: 'c1', phone: '(555) 300-0002' },
  { id: 'w3', name: 'Tyler Brooks', email: 'tyler@mitchell-plumbing.com', role: 'field_worker', companyId: 'c1', phone: '(555) 300-0003' },
  { id: 'w4', name: 'Mike Chen', email: 'mike@sparkvolt.com', role: 'field_worker', companyId: 'c2', phone: '(555) 300-0004' },
  { id: 'w5', name: 'Ahmed Hassan', email: 'ahmed@sparkvolt.com', role: 'field_worker', companyId: 'c2', phone: '(555) 300-0005' },
];

export const plans: SubscriptionPlan[] = [
  { id: 'p1', name: 'Basic', price: 49, billing: 'monthly', features: ['Up to 5 workers', '50 jobs/month', 'Basic reports', 'Email support'], maxWorkers: 5, maxJobs: 50 },
  { id: 'p2', name: 'Pro', price: 99, billing: 'monthly', features: ['Up to 20 workers', 'Unlimited jobs', 'Advanced reports', 'Priority support', 'Calendar view', 'Inventory management'], maxWorkers: 20, maxJobs: -1 },
  { id: 'p3', name: 'Enterprise', price: 249, billing: 'monthly', features: ['Unlimited workers', 'Unlimited jobs', 'Custom reports', 'Dedicated support', 'API access', 'White labeling', 'Multi-location'], maxWorkers: -1, maxJobs: -1 },
];

export const companies: Company[] = [
  { id: 'c1', name: 'Mitchell Plumbing Co.', email: 'info@mitchell-plumbing.com', phone: '(555) 201-1234', address: '742 Evergreen Terrace, Springfield, IL 62704', planId: 'p2', status: 'active', createdAt: '2024-01-15', adminId: 'a1', employeeCount: 12 },
  { id: 'c2', name: 'SparkVolt Electrical', email: 'contact@sparkvolt.com', phone: '(555) 202-5678', address: '1600 Pennsylvania Ave, Washington, DC 20500', planId: 'p3', status: 'active', createdAt: '2024-02-20', adminId: 'a2', employeeCount: 25 },
  { id: 'c3', name: 'CoolBreeze HVAC', email: 'hello@coolbreeze.com', phone: '(555) 203-9012', address: '350 Fifth Ave, New York, NY 10118', planId: 'p1', status: 'active', createdAt: '2024-03-10', adminId: 'a3', employeeCount: 8 },
  { id: 'c4', name: 'ProPipe Solutions', email: 'info@propipe.com', phone: '(555) 204-3456', address: '200 Park Ave, New York, NY 10166', planId: 'p2', status: 'trial', createdAt: '2024-06-01', adminId: '', employeeCount: 6 },
  { id: 'c5', name: 'ArcLight Electric', email: 'sales@arclight.com', phone: '(555) 205-7890', address: '100 Market St, San Francisco, CA 94105', planId: 'p1', status: 'suspended', createdAt: '2024-04-15', adminId: '', employeeCount: 3 },
];

const defaultAvailability = {
  monday: { start: '08:00', end: '17:00' },
  tuesday: { start: '08:00', end: '17:00' },
  wednesday: { start: '08:00', end: '17:00' },
  thursday: { start: '08:00', end: '17:00' },
  friday: { start: '08:00', end: '17:00' },
  saturday: null,
  sunday: null,
};

export const workers: Worker[] = [
  { id: 'w1', name: 'Jake Morrison', email: 'jake@mitchell-plumbing.com', phone: '(555) 300-0001', companyId: 'c1', specialties: ['Pipe repair', 'Water heater'], status: 'active', rating: 4.8, jobsCompleted: 234, availability: { ...defaultAvailability }, unavailableDates: ['2026-04-10', '2026-04-11'] },
  { id: 'w2', name: 'Carlos Rivera', email: 'carlos@mitchell-plumbing.com', phone: '(555) 300-0002', companyId: 'c1', specialties: ['Drain cleaning', 'Sewer'], status: 'active', rating: 4.6, jobsCompleted: 189, availability: { ...defaultAvailability, saturday: { start: '09:00', end: '14:00' } }, unavailableDates: [] },
  { id: 'w3', name: 'Tyler Brooks', email: 'tyler@mitchell-plumbing.com', phone: '(555) 300-0003', companyId: 'c1', specialties: ['Gas lines', 'Fixtures'], status: 'active', rating: 4.9, jobsCompleted: 312, availability: { ...defaultAvailability }, unavailableDates: ['2026-04-15'] },
  { id: 'w4', name: 'Lisa Park', email: 'lisa@mitchell-plumbing.com', phone: '(555) 300-0006', companyId: 'c1', specialties: ['Water heater', 'Bathroom remodel'], status: 'active', rating: 4.7, jobsCompleted: 156, availability: { ...defaultAvailability }, unavailableDates: [] },
  { id: 'w5', name: 'Omar Patel', email: 'omar@mitchell-plumbing.com', phone: '(555) 300-0007', companyId: 'c1', specialties: ['Emergency repair', 'Pipe repair'], status: 'on_leave', rating: 4.5, jobsCompleted: 98, availability: { ...defaultAvailability }, unavailableDates: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11', '2026-04-12', '2026-04-13'] },
  { id: 'w6', name: 'Mike Chen', email: 'mike@sparkvolt.com', phone: '(555) 300-0004', companyId: 'c2', specialties: ['Panel upgrade', 'Wiring'], status: 'active', rating: 4.7, jobsCompleted: 278, availability: { ...defaultAvailability }, unavailableDates: [] },
  { id: 'w7', name: 'Ahmed Hassan', email: 'ahmed@sparkvolt.com', phone: '(555) 300-0005', companyId: 'c2', specialties: ['EV charger', 'Smart home'], status: 'active', rating: 4.4, jobsCompleted: 145, availability: { ...defaultAvailability }, unavailableDates: [] },
  { id: 'w8', name: 'Rachel Kim', email: 'rachel@sparkvolt.com', phone: '(555) 300-0008', companyId: 'c2', specialties: ['Commercial wiring', 'Lighting'], status: 'active', rating: 4.9, jobsCompleted: 203, availability: { ...defaultAvailability }, unavailableDates: [] },
  { id: 'w9', name: 'James Wilson', email: 'james@coolbreeze.com', phone: '(555) 300-0009', companyId: 'c3', specialties: ['AC install', 'Duct work'], status: 'active', rating: 4.6, jobsCompleted: 167, availability: { ...defaultAvailability }, unavailableDates: [] },
  { id: 'w10', name: 'Maria Gonzalez', email: 'maria@coolbreeze.com', phone: '(555) 300-0010', companyId: 'c3', specialties: ['Furnace repair', 'Thermostat'], status: 'active', rating: 4.8, jobsCompleted: 201, availability: { ...defaultAvailability }, unavailableDates: [] },
];

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const addDays = (d: Date, n: number) => { const r = new Date(d); r.setDate(r.getDate() + n); return r; };

export const jobs: Job[] = [
  { id: 'j1', title: 'Water Heater Replacement', description: 'Replace 50-gallon gas water heater', status: 'in_progress', priority: 'high', companyId: 'c1', customerId: 'cust1', customerName: 'Robert Johnson', customerPhone: '(555) 400-0001', customerAddress: '123 Oak St, Springfield, IL', assignedWorkerId: 'w1', scheduledDate: fmt(today), scheduledTime: '09:00', estimatedDuration: 4, materials: ['50-gal water heater', 'Copper fittings', 'Gas flex line'], notes: ['Customer prefers tankless upgrade discussion'], images: [], createdAt: fmt(addDays(today, -2)), updatedAt: fmt(today), category: 'plumbing' },
  { id: 'j2', title: 'Kitchen Drain Clog', description: 'Severe kitchen drain blockage, possibly grease buildup', status: 'assigned', priority: 'medium', companyId: 'c1', customerId: 'cust2', customerName: 'Patricia Williams', customerPhone: '(555) 400-0002', customerAddress: '456 Maple Ave, Springfield, IL', assignedWorkerId: 'w2', scheduledDate: fmt(today), scheduledTime: '13:00', estimatedDuration: 2, materials: ['Drain snake', 'Bio-clean solution'], notes: [], images: [], createdAt: fmt(addDays(today, -1)), updatedAt: fmt(today), category: 'plumbing' },
  { id: 'j3', title: 'Bathroom Remodel Plumbing', description: 'Full bathroom remodel - rough-in and finish plumbing', status: 'new', priority: 'medium', companyId: 'c1', customerId: 'cust3', customerName: 'Michael Davis', customerPhone: '(555) 400-0003', customerAddress: '789 Elm Dr, Springfield, IL', scheduledDate: fmt(addDays(today, 3)), scheduledTime: '08:00', estimatedDuration: 8, materials: ['PEX tubing', 'SharkBite fittings', 'Toilet flange'], notes: ['Coordinate with tile contractor'], images: [], createdAt: fmt(addDays(today, -3)), updatedAt: fmt(addDays(today, -1)), category: 'plumbing' },
  { id: 'j4', title: 'Emergency Pipe Burst', description: 'Burst pipe in basement causing flooding', status: 'completed', priority: 'urgent', companyId: 'c1', customerId: 'cust4', customerName: 'Jennifer Brown', customerPhone: '(555) 400-0004', customerAddress: '321 Pine Rd, Springfield, IL', assignedWorkerId: 'w3', scheduledDate: fmt(addDays(today, -1)), scheduledTime: '07:00', estimatedDuration: 3, materials: ['Copper pipe 3/4"', 'Solder', 'Pipe insulation'], notes: ['Emergency call - after hours', 'Insurance claim filed'], images: [], createdAt: fmt(addDays(today, -1)), updatedAt: fmt(today), completedAt: fmt(today), category: 'plumbing' },
  { id: 'j5', title: 'Sewer Line Inspection', description: 'Camera inspection of main sewer line', status: 'assigned', priority: 'low', companyId: 'c1', customerId: 'cust5', customerName: 'Thomas Anderson', customerPhone: '(555) 400-0005', customerAddress: '654 Birch Ln, Springfield, IL', assignedWorkerId: 'w2', scheduledDate: fmt(addDays(today, 1)), scheduledTime: '10:00', estimatedDuration: 2, materials: ['Camera equipment'], notes: [], images: [], createdAt: fmt(addDays(today, -4)), updatedAt: fmt(addDays(today, -2)), category: 'plumbing' },
  { id: 'j6', title: 'Gas Line Installation', description: 'New gas line for outdoor kitchen', status: 'new', priority: 'high', companyId: 'c1', customerId: 'cust6', customerName: 'Linda Martinez', customerPhone: '(555) 400-0006', customerAddress: '987 Cedar Ct, Springfield, IL', scheduledDate: fmt(addDays(today, 5)), scheduledTime: '08:00', estimatedDuration: 6, materials: ['Black iron pipe', 'Gas fittings', 'Thread sealant'], notes: ['Requires permit - pending'], images: [], createdAt: fmt(addDays(today, -5)), updatedAt: fmt(addDays(today, -3)), category: 'plumbing' },
  { id: 'j7', title: 'Fixture Installation', description: 'Install new kitchen faucet and garbage disposal', status: 'in_progress', priority: 'low', companyId: 'c1', customerId: 'cust7', customerName: 'Barbara Wilson', customerPhone: '(555) 400-0007', customerAddress: '147 Walnut St, Springfield, IL', assignedWorkerId: 'w4', scheduledDate: fmt(today), scheduledTime: '14:00', estimatedDuration: 2, materials: ['Kitchen faucet - Delta', 'Garbage disposal 1/2 HP'], notes: [], images: [], createdAt: fmt(addDays(today, -2)), updatedAt: fmt(today), category: 'plumbing' },
  { id: 'j8', title: 'Water Softener Install', description: 'Install whole-house water softener system', status: 'assigned', priority: 'medium', companyId: 'c1', customerId: 'cust8', customerName: 'James Taylor', customerPhone: '(555) 400-0008', customerAddress: '258 Spruce Ave, Springfield, IL', assignedWorkerId: 'w1', scheduledDate: fmt(addDays(today, 2)), scheduledTime: '09:00', estimatedDuration: 4, materials: ['Water softener unit', 'Bypass valve', 'Salt'], notes: ['Test water hardness first'], images: [], createdAt: fmt(addDays(today, -6)), updatedAt: fmt(addDays(today, -4)), category: 'plumbing' },
  { id: 'j9', title: 'Sump Pump Replacement', description: 'Replace failed sump pump in basement', status: 'new', priority: 'high', companyId: 'c1', customerId: 'cust9', customerName: 'Elizabeth Moore', customerPhone: '(555) 400-0009', customerAddress: '369 Ash Blvd, Springfield, IL', scheduledDate: fmt(addDays(today, 1)), scheduledTime: '11:00', estimatedDuration: 3, materials: ['Sump pump 1/3 HP', 'Check valve', 'PVC pipe'], notes: [], images: [], createdAt: fmt(addDays(today, -1)), updatedAt: fmt(today), category: 'plumbing' },
  { id: 'j10', title: 'Leak Detection', description: 'Underground leak detection in front yard', status: 'completed', priority: 'medium', companyId: 'c1', customerId: 'cust10', customerName: 'Richard Clark', customerPhone: '(555) 400-0010', customerAddress: '741 Poplar Way, Springfield, IL', assignedWorkerId: 'w3', scheduledDate: fmt(addDays(today, -3)), scheduledTime: '10:00', estimatedDuration: 3, materials: ['Acoustic leak detector'], notes: ['Found leak at meter connection'], images: [], createdAt: fmt(addDays(today, -7)), updatedAt: fmt(addDays(today, -3)), completedAt: fmt(addDays(today, -3)), category: 'plumbing' },
  { id: 'j11', title: 'Panel Upgrade 200A', description: 'Upgrade electrical panel from 100A to 200A', status: 'in_progress', priority: 'high', companyId: 'c2', customerId: 'cust11', customerName: 'Steven Wright', customerPhone: '(555) 400-0011', customerAddress: '852 K St NW, Washington, DC', assignedWorkerId: 'w6', scheduledDate: fmt(today), scheduledTime: '08:00', estimatedDuration: 8, materials: ['200A panel', 'Main breaker', 'Wire #2 AWG'], notes: ['Utility disconnect scheduled'], images: [], createdAt: fmt(addDays(today, -3)), updatedAt: fmt(today), category: 'electrical' },
  { id: 'j12', title: 'EV Charger Installation', description: 'Install Level 2 EV charger in garage', status: 'assigned', priority: 'medium', companyId: 'c2', customerId: 'cust12', customerName: 'Nancy Adams', customerPhone: '(555) 400-0012', customerAddress: '963 L St NW, Washington, DC', assignedWorkerId: 'w7', scheduledDate: fmt(addDays(today, 1)), scheduledTime: '09:00', estimatedDuration: 4, materials: ['ChargePoint Home Flex', '40A breaker', '6 AWG wire'], notes: [], images: [], createdAt: fmt(addDays(today, -2)), updatedAt: fmt(addDays(today, -1)), category: 'electrical' },
  { id: 'j13', title: 'AC Unit Replacement', description: 'Replace 3-ton central AC unit', status: 'new', priority: 'high', companyId: 'c3', customerId: 'cust13', customerName: 'Karen Phillips', customerPhone: '(555) 400-0013', customerAddress: '159 W 45th St, New York, NY', scheduledDate: fmt(addDays(today, 4)), scheduledTime: '07:00', estimatedDuration: 8, materials: ['3-ton AC condenser', 'Refrigerant R-410A', 'Line set'], notes: ['Crane access needed for rooftop'], images: [], createdAt: fmt(addDays(today, -5)), updatedAt: fmt(addDays(today, -2)), category: 'hvac' },
  { id: 'j14', title: 'Furnace Repair', description: 'Furnace not igniting - pilot light issue', status: 'completed', priority: 'urgent', companyId: 'c3', customerId: 'cust14', customerName: 'Donald Evans', customerPhone: '(555) 400-0014', customerAddress: '267 Broadway, New York, NY', assignedWorkerId: 'w9', scheduledDate: fmt(addDays(today, -2)), scheduledTime: '08:00', estimatedDuration: 2, materials: ['Igniter', 'Flame sensor'], notes: ['Replaced igniter and flame sensor'], images: [], createdAt: fmt(addDays(today, -3)), updatedAt: fmt(addDays(today, -2)), completedAt: fmt(addDays(today, -2)), category: 'hvac' },
  // More jobs for company c1
  { id: 'j15', title: 'Toilet Replacement', description: 'Replace old toilet with low-flow model', status: 'completed', priority: 'low', companyId: 'c1', customerId: 'cust15', customerName: 'Susan Turner', customerPhone: '(555) 400-0015', customerAddress: '432 Hickory St, Springfield, IL', assignedWorkerId: 'w4', scheduledDate: fmt(addDays(today, -5)), scheduledTime: '10:00', estimatedDuration: 2, materials: ['Low-flow toilet', 'Wax ring', 'Supply line'], notes: [], images: [], createdAt: fmt(addDays(today, -8)), updatedAt: fmt(addDays(today, -5)), completedAt: fmt(addDays(today, -5)), category: 'plumbing' },
  { id: 'j16', title: 'Garbage Disposal Repair', description: 'Disposal making grinding noise', status: 'cancelled', priority: 'low', companyId: 'c1', customerId: 'cust16', customerName: 'Kevin White', customerPhone: '(555) 400-0016', customerAddress: '567 Oak Lane, Springfield, IL', scheduledDate: fmt(addDays(today, -4)), scheduledTime: '15:00', estimatedDuration: 1, materials: [], notes: ['Customer cancelled - fixed themselves'], images: [], createdAt: fmt(addDays(today, -6)), updatedAt: fmt(addDays(today, -4)), category: 'plumbing' },
  { id: 'j17', title: 'Shower Valve Replacement', description: 'Leaking shower valve in master bath', status: 'assigned', priority: 'medium', companyId: 'c1', customerId: 'cust17', customerName: 'Dorothy Harris', customerPhone: '(555) 400-0017', customerAddress: '890 Elm St, Springfield, IL', assignedWorkerId: 'w3', scheduledDate: fmt(addDays(today, 2)), scheduledTime: '13:00', estimatedDuration: 3, materials: ['Moen shower valve', 'Trim kit'], notes: [], images: [], createdAt: fmt(addDays(today, -3)), updatedAt: fmt(addDays(today, -1)), category: 'plumbing' },
  { id: 'j18', title: 'Tankless Water Heater', description: 'Install Rinnai tankless water heater', status: 'new', priority: 'medium', companyId: 'c1', customerId: 'cust18', customerName: 'George Clark', customerPhone: '(555) 400-0018', customerAddress: '234 Cherry Dr, Springfield, IL', scheduledDate: fmt(addDays(today, 6)), scheduledTime: '08:00', estimatedDuration: 6, materials: ['Rinnai tankless unit', 'Venting kit', 'Gas line components'], notes: ['Customer wants concentric venting'], images: [], createdAt: fmt(addDays(today, -2)), updatedAt: fmt(addDays(today, -1)), category: 'plumbing' },
  { id: 'j19', title: 'Backflow Preventer Test', description: 'Annual backflow preventer testing', status: 'assigned', priority: 'low', companyId: 'c1', customerId: 'cust19', customerName: 'Helen Lewis', customerPhone: '(555) 400-0019', customerAddress: '678 Willow Rd, Springfield, IL', assignedWorkerId: 'w2', scheduledDate: fmt(addDays(today, 3)), scheduledTime: '09:00', estimatedDuration: 1, materials: ['Test gauge kit'], notes: [], images: [], createdAt: fmt(addDays(today, -7)), updatedAt: fmt(addDays(today, -5)), category: 'plumbing' },
  { id: 'j20', title: 'Main Line Replacement', description: 'Replace corroded main water line', status: 'new', priority: 'high', companyId: 'c1', customerId: 'cust20', customerName: 'Mark Robinson', customerPhone: '(555) 400-0020', customerAddress: '901 Magnolia Ct, Springfield, IL', scheduledDate: fmt(addDays(today, 7)), scheduledTime: '07:00', estimatedDuration: 10, materials: ['1" copper pipe 50ft', 'Compression fittings', 'Backfill material'], notes: ['Requires excavation - call 811 first'], images: [], createdAt: fmt(addDays(today, -1)), updatedAt: fmt(today), category: 'plumbing' },
];

export const inventory: InventoryItem[] = [
  { id: 'inv1', name: 'Copper Pipe 3/4"', sku: 'CP-075', category: 'Pipes', quantity: 150, minStock: 50, unitPrice: 8.50, companyId: 'c1' },
  { id: 'inv2', name: 'PEX Tubing 1/2" (100ft)', sku: 'PEX-050', category: 'Pipes', quantity: 25, minStock: 10, unitPrice: 45.00, companyId: 'c1' },
  { id: 'inv3', name: 'SharkBite Fitting 3/4"', sku: 'SB-075', category: 'Fittings', quantity: 8, minStock: 20, unitPrice: 12.75, companyId: 'c1' },
  { id: 'inv4', name: 'Pipe Solder (1lb)', sku: 'SOL-001', category: 'Supplies', quantity: 30, minStock: 15, unitPrice: 15.00, companyId: 'c1' },
  { id: 'inv5', name: 'Wax Ring w/ Horn', sku: 'WR-001', category: 'Toilet Parts', quantity: 45, minStock: 20, unitPrice: 4.50, companyId: 'c1' },
  { id: 'inv6', name: 'Supply Line 3/8"x12"', sku: 'SL-312', category: 'Supplies', quantity: 60, minStock: 25, unitPrice: 6.25, companyId: 'c1' },
  { id: 'inv7', name: 'Gas Flex Line 3/4"', sku: 'GFL-075', category: 'Gas', quantity: 12, minStock: 8, unitPrice: 22.00, companyId: 'c1' },
  { id: 'inv8', name: 'Drain Snake 25ft', sku: 'DS-025', category: 'Tools', quantity: 5, minStock: 3, unitPrice: 89.00, companyId: 'c1' },
  { id: 'inv9', name: 'Bio-Clean Solution (2lb)', sku: 'BC-002', category: 'Chemicals', quantity: 3, minStock: 10, unitPrice: 55.00, companyId: 'c1' },
  { id: 'inv10', name: 'Toilet Flange PVC', sku: 'TF-PVC', category: 'Toilet Parts', quantity: 35, minStock: 15, unitPrice: 7.50, companyId: 'c1' },
  { id: 'inv11', name: '200A Main Breaker Panel', sku: 'MB-200', category: 'Panels', quantity: 3, minStock: 2, unitPrice: 385.00, companyId: 'c2' },
  { id: 'inv12', name: '6 AWG Wire (100ft)', sku: 'W6-100', category: 'Wire', quantity: 15, minStock: 5, unitPrice: 125.00, companyId: 'c2' },
];

export const invoices: Invoice[] = [
  { id: 'inv-1', invoiceNumber: 'INV-2026-001', jobId: 'j4', companyId: 'c1', customerName: 'Jennifer Brown', amount: 850, tax: 68, total: 918, status: 'paid', createdAt: fmt(addDays(today, -1)), dueDate: fmt(addDays(today, 29)), items: [{ description: 'Emergency pipe repair - labor', quantity: 3, unitPrice: 150, total: 450 }, { description: 'Copper pipe 3/4"', quantity: 10, unitPrice: 8.50, total: 85 }, { description: 'Emergency call-out fee', quantity: 1, unitPrice: 315, total: 315 }] },
  { id: 'inv-2', invoiceNumber: 'INV-2026-002', jobId: 'j10', companyId: 'c1', customerName: 'Richard Clark', amount: 425, tax: 34, total: 459, status: 'sent', createdAt: fmt(addDays(today, -3)), dueDate: fmt(addDays(today, 27)), items: [{ description: 'Leak detection service', quantity: 3, unitPrice: 125, total: 375 }, { description: 'Equipment rental', quantity: 1, unitPrice: 50, total: 50 }] },
  { id: 'inv-3', invoiceNumber: 'INV-2026-003', jobId: 'j15', companyId: 'c1', customerName: 'Susan Turner', amount: 380, tax: 30.40, total: 410.40, status: 'paid', createdAt: fmt(addDays(today, -5)), dueDate: fmt(addDays(today, 25)), items: [{ description: 'Toilet replacement - labor', quantity: 2, unitPrice: 125, total: 250 }, { description: 'Low-flow toilet', quantity: 1, unitPrice: 110, total: 110 }, { description: 'Wax ring & supply line', quantity: 1, unitPrice: 20, total: 20 }] },
  { id: 'inv-4', invoiceNumber: 'INV-2026-004', jobId: 'j1', companyId: 'c1', customerName: 'Robert Johnson', amount: 1200, tax: 96, total: 1296, status: 'draft', createdAt: fmt(today), dueDate: fmt(addDays(today, 30)), items: [{ description: 'Water heater replacement - labor', quantity: 4, unitPrice: 150, total: 600 }, { description: '50-gal gas water heater', quantity: 1, unitPrice: 550, total: 550 }, { description: 'Fittings & materials', quantity: 1, unitPrice: 50, total: 50 }] },
  { id: 'inv-5', invoiceNumber: 'INV-2026-005', jobId: 'j11', companyId: 'c2', customerName: 'Steven Wright', amount: 3200, tax: 256, total: 3456, status: 'draft', createdAt: fmt(today), dueDate: fmt(addDays(today, 30)), items: [{ description: 'Panel upgrade - labor', quantity: 8, unitPrice: 175, total: 1400 }, { description: '200A panel', quantity: 1, unitPrice: 385, total: 385 }, { description: 'Wire & breakers', quantity: 1, unitPrice: 1415, total: 1415 }] },
  { id: 'inv-6', invoiceNumber: 'INV-2026-006', jobId: 'j14', companyId: 'c3', customerName: 'Donald Evans', amount: 350, tax: 28, total: 378, status: 'overdue', createdAt: fmt(addDays(today, -10)), dueDate: fmt(addDays(today, -3)), items: [{ description: 'Furnace repair - labor', quantity: 2, unitPrice: 125, total: 250 }, { description: 'Igniter & flame sensor', quantity: 1, unitPrice: 100, total: 100 }] },
];

export const chatMessages: ChatMessage[] = [
  { id: 'msg1', senderId: 'a1', senderName: 'Sarah Mitchell', receiverId: 'w1', message: 'Jake, the water heater for 123 Oak St is ready for pickup at the warehouse.', timestamp: `${fmt(today)}T08:30:00`, read: true },
  { id: 'msg2', senderId: 'w1', senderName: 'Jake Morrison', receiverId: 'a1', message: 'Got it! Heading there now. Should I grab extra fittings?', timestamp: `${fmt(today)}T08:35:00`, read: true },
  { id: 'msg3', senderId: 'a1', senderName: 'Sarah Mitchell', receiverId: 'w1', message: 'Yes, grab a couple 3/4" copper fittings and a gas flex line just in case.', timestamp: `${fmt(today)}T08:37:00`, read: true },
  { id: 'msg4', senderId: 'w1', senderName: 'Jake Morrison', receiverId: 'a1', message: 'On site now. Old unit is disconnected. Starting install.', timestamp: `${fmt(today)}T10:15:00`, read: false },
  { id: 'msg5', senderId: 'a1', senderName: 'Sarah Mitchell', receiverId: 'w2', message: 'Carlos, how\'s the drain job going at 456 Maple Ave?', timestamp: `${fmt(today)}T13:30:00`, read: false },
  { id: 'msg6', senderId: 'w2', senderName: 'Carlos Rivera', receiverId: 'a1', message: 'Haven\'t started yet, heading over after lunch.', timestamp: `${fmt(today)}T13:32:00`, read: true },
];

export const notifications: Notification[] = [
  { id: 'n1', userId: 'a1', title: 'Emergency Job Completed', message: 'Jake Morrison completed emergency pipe repair at 321 Pine Rd', type: 'success', read: false, timestamp: `${fmt(today)}T11:00:00` },
  { id: 'n2', userId: 'a1', title: 'Low Stock Alert', message: 'SharkBite Fitting 3/4" is below minimum stock level (8/20)', type: 'warning', read: false, timestamp: `${fmt(today)}T09:00:00` },
  { id: 'n3', userId: 'a1', title: 'Low Stock Alert', message: 'Bio-Clean Solution is below minimum stock level (3/10)', type: 'warning', read: false, timestamp: `${fmt(today)}T09:00:00` },
  { id: 'n4', userId: 'a1', title: 'New Job Request', message: 'New job request: Main Line Replacement at 901 Magnolia Ct', type: 'info', read: true, timestamp: `${fmt(today)}T08:00:00` },
  { id: 'n5', userId: 'w1', title: 'New Assignment', message: 'You have been assigned: Water Heater Replacement at 123 Oak St', type: 'info', read: true, timestamp: `${fmt(addDays(today, -1))}T17:00:00` },
  { id: 'n6', userId: 'sa1', title: 'New Company Registered', message: 'ProPipe Solutions has started a trial subscription', type: 'info', read: false, timestamp: `${fmt(addDays(today, -1))}T14:00:00` },
];

export const documents: Document[] = [
  { id: 'doc1', name: 'Plumbing License.pdf', type: 'PDF', size: '2.4 MB', companyId: 'c1', uploadedAt: '2024-01-15', uploadedBy: 'Sarah Mitchell' },
  { id: 'doc2', name: 'Insurance Certificate.pdf', type: 'PDF', size: '1.8 MB', companyId: 'c1', uploadedAt: '2024-01-15', uploadedBy: 'Sarah Mitchell' },
  { id: 'doc3', name: 'Water Heater Warranty.pdf', type: 'PDF', size: '520 KB', jobId: 'j1', companyId: 'c1', uploadedAt: fmt(addDays(today, -2)), uploadedBy: 'Jake Morrison' },
  { id: 'doc4', name: 'Pipe Inspection Report.pdf', type: 'PDF', size: '3.1 MB', jobId: 'j10', companyId: 'c1', uploadedAt: fmt(addDays(today, -3)), uploadedBy: 'Tyler Brooks' },
  { id: 'doc5', name: 'Job Photos - Pine Rd.zip', type: 'ZIP', size: '15.2 MB', jobId: 'j4', companyId: 'c1', uploadedAt: fmt(today), uploadedBy: 'Tyler Brooks' },
];

export const serviceAgreements: ServiceAgreement[] = [
  { id: 'sa-1', title: 'Annual Maintenance - Johnson Residence', customerName: 'Robert Johnson', companyId: 'c1', jobId: 'j1', status: 'active', startDate: '2026-01-01', endDate: '2026-12-31', terms: 'Quarterly plumbing inspection and maintenance. Includes priority scheduling and 10% discount on repairs.' },
  { id: 'sa-2', title: 'Emergency Service Agreement - Clark', customerName: 'Richard Clark', companyId: 'c1', status: 'active', startDate: '2025-06-01', endDate: '2026-05-31', terms: '24/7 emergency service guarantee with 2-hour response time. Monthly retainer includes 2 free service calls.' },
  { id: 'sa-3', title: 'Commercial Maintenance - Office Complex', customerName: 'Greenfield Properties LLC', companyId: 'c1', status: 'draft', startDate: '2026-05-01', endDate: '2027-04-30', terms: 'Monthly plumbing maintenance for 5-story office complex. Includes all common area fixtures and water heater service.' },
];

export const emailTemplates: EmailTemplate[] = [
  { id: 'et1', name: 'Invoice Notification', subject: 'Invoice #{invoiceNumber} from {companyName}', body: 'Dear {customerName},\n\nPlease find attached invoice #{invoiceNumber} for the services rendered.\n\nAmount Due: ${amount}\nDue Date: {dueDate}\n\nThank you for choosing {companyName}.\n\nBest regards,\n{companyName}', companyId: 'c1', type: 'invoice' },
  { id: 'et2', name: 'Appointment Reminder', subject: 'Appointment Reminder - {jobTitle}', body: 'Dear {customerName},\n\nThis is a reminder of your upcoming appointment:\n\nService: {jobTitle}\nDate: {scheduledDate}\nTime: {scheduledTime}\nTechnician: {workerName}\n\nPlease ensure access to the work area.\n\nBest regards,\n{companyName}', companyId: 'c1', type: 'appointment' },
  { id: 'et3', name: 'Follow-Up Survey', subject: 'How was your experience with {companyName}?', body: 'Dear {customerName},\n\nThank you for choosing {companyName}! We hope the service met your expectations.\n\nWe would love to hear your feedback. Please take a moment to rate your experience.\n\nBest regards,\n{companyName}', companyId: 'c1', type: 'follow_up' },
];

export const customers: Customer[] = [
  { id: 'cust1', name: 'Robert Johnson', email: 'robert.johnson@email.com', phone: '(555) 400-0001', address: '123 Oak St, Springfield, IL', companyId: 'c1', notes: 'Prefers morning appointments. Has 2 dogs.', tags: ['VIP', 'Repeat'], status: 'active', createdAt: '2024-03-15', totalJobs: 5, totalSpent: 4250 },
  { id: 'cust2', name: 'Patricia Williams', email: 'patricia.w@email.com', phone: '(555) 400-0002', address: '456 Maple Ave, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'active', createdAt: '2024-06-20', totalJobs: 2, totalSpent: 890 },
  { id: 'cust3', name: 'Michael Davis', email: 'mdavis@email.com', phone: '(555) 400-0003', address: '789 Elm Dr, Springfield, IL', companyId: 'c1', notes: 'Renovation project ongoing through Q2', tags: ['Renovation', 'High-Value'], status: 'active', createdAt: '2024-08-10', totalJobs: 3, totalSpent: 12500 },
  { id: 'cust4', name: 'Jennifer Brown', email: 'jbrown@email.com', phone: '(555) 400-0004', address: '321 Pine Rd, Springfield, IL', companyId: 'c1', notes: 'Insurance claim for pipe burst', tags: ['Insurance'], status: 'active', createdAt: '2025-01-05', totalJobs: 1, totalSpent: 1850 },
  { id: 'cust5', name: 'Thomas Anderson', email: 'tanderson@email.com', phone: '(555) 400-0005', address: '654 Birch Ln, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'active', createdAt: '2024-11-12', totalJobs: 2, totalSpent: 650 },
  { id: 'cust6', name: 'Linda Martinez', email: 'lmartinez@email.com', phone: '(555) 400-0006', address: '987 Cedar Ct, Springfield, IL', companyId: 'c1', notes: 'Outdoor kitchen project. Permit pending.', tags: ['Outdoor', 'Permit-Required'], status: 'active', createdAt: '2025-02-18', totalJobs: 1, totalSpent: 0 },
  { id: 'cust7', name: 'Barbara Wilson', email: 'bwilson@email.com', phone: '(555) 400-0007', address: '147 Walnut St, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'active', createdAt: '2024-09-03', totalJobs: 4, totalSpent: 2100 },
  { id: 'cust8', name: 'James Taylor', email: 'jtaylor@email.com', phone: '(555) 400-0008', address: '258 Spruce Ave, Springfield, IL', companyId: 'c1', notes: 'Interested in water filtration after softener install', tags: ['Upsell'], status: 'active', createdAt: '2024-07-22', totalJobs: 2, totalSpent: 1500 },
  { id: 'cust9', name: 'Elizabeth Moore', email: 'emoore@email.com', phone: '(555) 400-0009', address: '369 Ash Blvd, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'active', createdAt: '2025-03-01', totalJobs: 1, totalSpent: 0 },
  { id: 'cust10', name: 'Richard Clark', email: 'rclark@email.com', phone: '(555) 400-0010', address: '741 Poplar Way, Springfield, IL', companyId: 'c1', notes: 'Has annual service agreement', tags: ['VIP', 'Agreement'], status: 'active', createdAt: '2024-01-20', totalJobs: 6, totalSpent: 3800 },
  { id: 'cust11', name: 'Steven Wright', email: 'swright@email.com', phone: '(555) 400-0011', address: '852 K St NW, Washington, DC', companyId: 'c2', notes: 'Panel upgrade for EV charger prep', tags: ['Electrical', 'EV'], status: 'active', createdAt: '2025-01-10', totalJobs: 1, totalSpent: 3456 },
  { id: 'cust12', name: 'Nancy Adams', email: 'nadams@email.com', phone: '(555) 400-0012', address: '963 L St NW, Washington, DC', companyId: 'c2', notes: '', tags: ['EV'], status: 'active', createdAt: '2025-02-05', totalJobs: 1, totalSpent: 0 },
  { id: 'cust13', name: 'Karen Phillips', email: 'kphillips@email.com', phone: '(555) 400-0013', address: '159 W 45th St, New York, NY', companyId: 'c3', notes: 'Rooftop unit - crane required', tags: ['Commercial'], status: 'active', createdAt: '2024-12-15', totalJobs: 1, totalSpent: 0 },
  { id: 'cust14', name: 'Donald Evans', email: 'devans@email.com', phone: '(555) 400-0014', address: '267 Broadway, New York, NY', companyId: 'c3', notes: '', tags: ['HVAC'], status: 'active', createdAt: '2025-01-03', totalJobs: 1, totalSpent: 378 },
  { id: 'cust15', name: 'Susan Turner', email: 'sturner@email.com', phone: '(555) 400-0015', address: '432 Hickory St, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'inactive', createdAt: '2024-04-10', totalJobs: 1, totalSpent: 450 },
  { id: 'cust16', name: 'Kevin White', email: 'kwhite@email.com', phone: '(555) 400-0016', address: '567 Oak Lane, Springfield, IL', companyId: 'c1', notes: 'Cancelled last job', tags: [], status: 'inactive', createdAt: '2024-05-15', totalJobs: 0, totalSpent: 0 },
  { id: 'cust17', name: 'Dorothy Harris', email: 'dharris@email.com', phone: '(555) 400-0017', address: '890 Elm St, Springfield, IL', companyId: 'c1', notes: '', tags: ['Residential'], status: 'active', createdAt: '2025-03-10', totalJobs: 1, totalSpent: 0 },
  { id: 'cust18', name: 'George Clark', email: 'gclark@email.com', phone: '(555) 400-0018', address: '234 Cherry Dr, Springfield, IL', companyId: 'c1', notes: 'Wants concentric venting for tankless', tags: ['Residential', 'Tankless'], status: 'lead', createdAt: '2025-03-20', totalJobs: 0, totalSpent: 0 },
  { id: 'cust19', name: 'Helen Lewis', email: 'hlewis@email.com', phone: '(555) 400-0019', address: '678 Willow Rd, Springfield, IL', companyId: 'c1', notes: 'Annual backflow testing', tags: ['Annual', 'Compliance'], status: 'active', createdAt: '2024-02-28', totalJobs: 3, totalSpent: 450 },
  { id: 'cust20', name: 'Mark Robinson', email: 'mrobinson@email.com', phone: '(555) 400-0020', address: '901 Magnolia Ct, Springfield, IL', companyId: 'c1', notes: 'Main line corroded - needs excavation. Call 811 first.', tags: ['High-Value', 'Excavation'], status: 'active', createdAt: '2025-04-01', totalJobs: 1, totalSpent: 0 },
];

const today2 = new Date();
const fmt2 = (d: Date) => d.toISOString().split('T')[0];
const addDays2 = (d: Date, n: number) => { const r = new Date(d); r.setDate(r.getDate() + n); return r; };

export const estimates: Estimate[] = [
  { id: 'est1', estimateNumber: 'EST-2026-001', companyId: 'c1', customerId: 'cust3', customerName: 'Michael Davis', customerEmail: 'mdavis@email.com', customerPhone: '(555) 400-0003', customerAddress: '789 Elm Dr, Springfield, IL', status: 'approved', items: [{ description: 'Bathroom remodel - rough-in plumbing', quantity: 8, unitPrice: 150, total: 1200 }, { description: 'PEX tubing & fittings', quantity: 1, unitPrice: 350, total: 350 }, { description: 'Fixtures (toilet, faucet, shower valve)', quantity: 1, unitPrice: 850, total: 850 }], subtotal: 2400, tax: 192, total: 2592, notes: 'Coordinate with tile contractor. Customer wants rain shower head.', validUntil: fmt2(addDays2(today2, 30)), createdAt: fmt2(addDays2(today2, -10)), updatedAt: fmt2(addDays2(today2, -3)), category: 'plumbing' },
  { id: 'est2', estimateNumber: 'EST-2026-002', companyId: 'c1', customerId: 'cust6', customerName: 'Linda Martinez', customerEmail: 'lmartinez@email.com', customerPhone: '(555) 400-0006', customerAddress: '987 Cedar Ct, Springfield, IL', status: 'sent', items: [{ description: 'Gas line installation - labor', quantity: 6, unitPrice: 175, total: 1050 }, { description: 'Black iron pipe & fittings', quantity: 1, unitPrice: 420, total: 420 }, { description: 'Permit fees', quantity: 1, unitPrice: 150, total: 150 }], subtotal: 1620, tax: 129.60, total: 1749.60, notes: 'Outdoor kitchen gas line. Permit pending approval.', validUntil: fmt2(addDays2(today2, 21)), createdAt: fmt2(addDays2(today2, -5)), updatedAt: fmt2(addDays2(today2, -2)), category: 'plumbing' },
  { id: 'est3', estimateNumber: 'EST-2026-003', companyId: 'c1', customerId: 'cust18', customerName: 'George Clark', customerEmail: 'gclark@email.com', customerPhone: '(555) 400-0018', customerAddress: '234 Cherry Dr, Springfield, IL', status: 'draft', items: [{ description: 'Tankless water heater installation - labor', quantity: 6, unitPrice: 150, total: 900 }, { description: 'Rinnai RU199iN tankless unit', quantity: 1, unitPrice: 1650, total: 1650 }, { description: 'Concentric venting kit', quantity: 1, unitPrice: 280, total: 280 }, { description: 'Gas line modification', quantity: 1, unitPrice: 350, total: 350 }], subtotal: 3180, tax: 254.40, total: 3434.40, notes: 'Customer prefers concentric venting. Includes removal of old tank unit.', validUntil: fmt2(addDays2(today2, 45)), createdAt: fmt2(addDays2(today2, -2)), updatedAt: fmt2(addDays2(today2, -1)), category: 'plumbing' },
  { id: 'est4', estimateNumber: 'EST-2026-004', companyId: 'c1', customerId: 'cust20', customerName: 'Mark Robinson', customerEmail: 'mrobinson@email.com', customerPhone: '(555) 400-0020', customerAddress: '901 Magnolia Ct, Springfield, IL', status: 'approved', items: [{ description: 'Main line excavation & replacement', quantity: 10, unitPrice: 200, total: 2000 }, { description: '1" copper pipe 50ft', quantity: 1, unitPrice: 450, total: 450 }, { description: 'Backfill & restoration', quantity: 1, unitPrice: 800, total: 800 }], subtotal: 3250, tax: 260, total: 3510, notes: 'Call 811 before digging. Will need excavator rental.', validUntil: fmt2(addDays2(today2, 14)), createdAt: fmt2(addDays2(today2, -7)), updatedAt: fmt2(addDays2(today2, -1)), category: 'plumbing' },
  { id: 'est5', estimateNumber: 'EST-2026-005', companyId: 'c1', customerId: 'cust7', customerName: 'Barbara Wilson', customerEmail: 'bwilson@email.com', customerPhone: '(555) 400-0007', customerAddress: '147 Walnut St, Springfield, IL', status: 'rejected', items: [{ description: 'Whole house re-pipe - labor', quantity: 16, unitPrice: 150, total: 2400 }, { description: 'PEX tubing (500ft)', quantity: 1, unitPrice: 225, total: 225 }, { description: 'Fittings & connections', quantity: 1, unitPrice: 350, total: 350 }], subtotal: 2975, tax: 238, total: 3213, notes: 'Customer felt price was too high. May revisit in Q3.', validUntil: fmt2(addDays2(today2, -5)), createdAt: fmt2(addDays2(today2, -20)), updatedAt: fmt2(addDays2(today2, -8)), category: 'plumbing' },
  { id: 'est6', estimateNumber: 'EST-2026-006', companyId: 'c1', customerId: 'cust8', customerName: 'James Taylor', customerEmail: 'jtaylor@email.com', customerPhone: '(555) 400-0008', customerAddress: '258 Spruce Ave, Springfield, IL', status: 'converted', items: [{ description: 'Water softener installation - labor', quantity: 4, unitPrice: 125, total: 500 }, { description: 'Water softener unit', quantity: 1, unitPrice: 650, total: 650 }, { description: 'Bypass valve & salt', quantity: 1, unitPrice: 85, total: 85 }], subtotal: 1235, tax: 98.80, total: 1333.80, notes: 'Converted to Job j8.', validUntil: fmt2(addDays2(today2, -10)), createdAt: fmt2(addDays2(today2, -30)), updatedAt: fmt2(addDays2(today2, -20)), convertedJobId: 'j8', category: 'plumbing' },
  { id: 'est7', estimateNumber: 'EST-2026-007', companyId: 'c2', customerId: 'cust11', customerName: 'Steven Wright', customerEmail: 'swright@email.com', customerPhone: '(555) 400-0011', customerAddress: '852 K St NW, Washington, DC', status: 'converted', items: [{ description: 'Panel upgrade 200A - labor', quantity: 8, unitPrice: 175, total: 1400 }, { description: '200A panel & main breaker', quantity: 1, unitPrice: 385, total: 385 }, { description: 'Wire & breakers', quantity: 1, unitPrice: 1415, total: 1415 }], subtotal: 3200, tax: 256, total: 3456, notes: 'Converted to Job j11.', validUntil: fmt2(addDays2(today2, -15)), createdAt: fmt2(addDays2(today2, -25)), updatedAt: fmt2(addDays2(today2, -15)), convertedJobId: 'j11', category: 'electrical' },
];

const nowMinus = (mins: number) => new Date(Date.now() - mins * 60_000).toISOString();
const COMPANY_LINE_C1 = '(555) 201-1234';
const COMPANY_LINE_C2 = '(555) 202-5678';
const COMPANY_LINE_C3 = '(555) 203-9012';

export const communications: Communication[] = [
  // Robert Johnson (cust1) — Job j1 (water heater replacement, w1 Jake)
  { id: 'cm1', companyId: 'c1', type: 'call', direction: 'inbound', status: 'completed', fromNumber: '(555) 400-0001', toNumber: COMPANY_LINE_C1, customerId: 'cust1', userId: 'a1', userName: 'Sarah Mitchell', durationSec: 312, body: 'Customer called to confirm tomorrow\'s appointment and asked about tankless options.', read: true, timestamp: nowMinus(60 * 26) },
  { id: 'cm2', companyId: 'c1', type: 'sms', direction: 'outbound', status: 'delivered', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0001', customerId: 'cust1', jobId: 'j1', userId: 'a1', userName: 'Sarah Mitchell', body: 'Hi Robert, Jake will arrive between 9-10am tomorrow for the water heater replacement. Reply STOP to opt out.', read: true, timestamp: nowMinus(60 * 25) },
  { id: 'cm3', companyId: 'c1', type: 'sms', direction: 'inbound', status: 'received', fromNumber: '(555) 400-0001', toNumber: COMPANY_LINE_C1, customerId: 'cust1', jobId: 'j1', body: 'Perfect, thank you! The dogs will be in the back yard.', read: true, timestamp: nowMinus(60 * 24) },
  { id: 'cm4', companyId: 'c1', type: 'call', direction: 'outbound', status: 'completed', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0001', customerId: 'cust1', jobId: 'j1', userId: 'w1', userName: 'Jake Morrison', durationSec: 95, body: 'En-route call from tech. ETA 15 minutes.', read: false, timestamp: nowMinus(45) },

  // Patricia Williams (cust2) — Job j2 drain
  { id: 'cm5', companyId: 'c1', type: 'voicemail', direction: 'inbound', status: 'completed', fromNumber: '(555) 400-0002', toNumber: COMPANY_LINE_C1, customerId: 'cust2', userId: 'a1', userName: 'Sarah Mitchell', durationSec: 42, body: 'Hi, this is Patricia. The kitchen drain is completely backed up now, please call me back ASAP. Thanks.', read: false, timestamp: nowMinus(60 * 5) },
  { id: 'cm6', companyId: 'c1', type: 'call', direction: 'outbound', status: 'completed', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0002', customerId: 'cust2', jobId: 'j2', userId: 'a1', userName: 'Sarah Mitchell', durationSec: 188, body: 'Returned voicemail. Confirmed Carlos will be there at 1pm.', read: true, timestamp: nowMinus(60 * 4) },

  // Michael Davis (cust3) — Estimate est1 + Job j3
  { id: 'cm7', companyId: 'c1', type: 'sms', direction: 'outbound', status: 'delivered', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0003', customerId: 'cust3', estimateId: 'est1', userId: 'a1', userName: 'Sarah Mitchell', body: 'Hi Michael, your bathroom remodel estimate (EST-2026-001) is ready. Total: $2,592. Let us know if you have questions!', read: true, timestamp: nowMinus(60 * 60 * 24 * 3) },
  { id: 'cm8', companyId: 'c1', type: 'sms', direction: 'inbound', status: 'received', fromNumber: '(555) 400-0003', toNumber: COMPANY_LINE_C1, customerId: 'cust3', estimateId: 'est1', body: 'Looks good. Approved! When can we start?', read: true, timestamp: nowMinus(60 * 60 * 24 * 3 - 60 * 30) },

  // Jennifer Brown (cust4) — Emergency Job j4
  { id: 'cm9', companyId: 'c1', type: 'call', direction: 'inbound', status: 'completed', fromNumber: '(555) 400-0004', toNumber: COMPANY_LINE_C1, customerId: 'cust4', jobId: 'j4', userId: 'a1', userName: 'Sarah Mitchell', durationSec: 540, body: 'Emergency intake call. Pipe burst in basement. Dispatched Tyler.', read: true, timestamp: nowMinus(60 * 60 * 25) },
  { id: 'cm10', companyId: 'c1', type: 'call', direction: 'outbound', status: 'no_answer', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0004', customerId: 'cust4', jobId: 'j4', userId: 'a1', userName: 'Sarah Mitchell', durationSec: 0, body: 'Follow-up after completion. No answer.', read: true, timestamp: nowMinus(60 * 60 * 2) },

  // Linda Martinez (cust6) — Estimate est2
  { id: 'cm11', companyId: 'c1', type: 'sms', direction: 'outbound', status: 'delivered', fromNumber: COMPANY_LINE_C1, toNumber: '(555) 400-0006', customerId: 'cust6', estimateId: 'est2', userId: 'a1', userName: 'Sarah Mitchell', body: 'Hi Linda, gas line estimate sent. We\'re still waiting on permit approval before scheduling.', read: true, timestamp: nowMinus(60 * 60 * 48) },

  // George Clark (cust18) — Estimate est3 (lead)
  { id: 'cm12', companyId: 'c1', type: 'call', direction: 'inbound', status: 'missed', fromNumber: '(555) 400-0018', toNumber: COMPANY_LINE_C1, customerId: 'cust18', durationSec: 0, body: '', read: false, timestamp: nowMinus(90) },
  { id: 'cm13', companyId: 'c1', type: 'voicemail', direction: 'inbound', status: 'completed', fromNumber: '(555) 400-0018', toNumber: COMPANY_LINE_C1, customerId: 'cust18', durationSec: 28, body: 'Hi this is George, calling about the tankless water heater quote. Wondering if we can move forward. Thanks.', read: false, timestamp: nowMinus(89) },

  // Steven Wright (cust11, c2)
  { id: 'cm14', companyId: 'c2', type: 'sms', direction: 'outbound', status: 'delivered', fromNumber: COMPANY_LINE_C2, toNumber: '(555) 400-0011', customerId: 'cust11', jobId: 'j11', userId: 'a2', userName: 'David Rodriguez', body: 'Steven, panel upgrade scheduled for Friday 8am. Mike will be onsite all day.', read: true, timestamp: nowMinus(60 * 60 * 8) },
];
