DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fieldpro_app') THEN
    CREATE ROLE fieldpro_app LOGIN PASSWORD 'admin' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO fieldpro_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO fieldpro_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fieldpro_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO fieldpro_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fieldpro_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO fieldpro_app;

DO $$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO fieldpro_app', current_database());
END $$;
